### ISSUE TITLE
About BAM file error  

### ISSUE THREAD

**Issue by YijiaChi** [Xinglab/rmats2sashimiplot#101]
Hello rMATS Team,
I am trying to run rmats2sashimiplot on my rmats output and bam files aligned by STAR. Here is the ERROR I met:

```
Plotting read densities and MISO estimates along event...
  - Event: chrKI270897.1:295983:296093:+@chrKI270897.1:296623:296731:+@chrKI270897.1:302360:302937:+
Setting up plot using dimensions:  [8.0, 7.0]
Using intron scale  1.0
Using exon scale  1.0
Reading sample label: SMN2 DMSO-1 IncLevel: 0.00
Error retrieving files from chrKI270897.1: invalid reference `chrKI270897.1`
Are you sure chrKI270897.1 appears in your BAM file?

Aborting plot...
Traceback (most recent call last):
  File "/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <m          odule>
    main()
  File "/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in ma          in
    plot_label=plot_label)
  File "/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in pl          ot_event
    plot_label=plot_label)
  File "/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 83          8, in plot_density_from_file
    plot_title=plot_title)
  File "/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 39          2, in plot_density
    junction_log_base=junction_log_base)
TypeError: 'AxesSubplot' object is not iterable
mv: cannot stat '/home/vg3/yijia/RNA-seq/Splicing/results/Plot12-star-test/Sashimi_plot/chrKI270897.1:295983:296093:+@chrKI27089          7.1:296623:296731:+@chrKI270897.1:302360:302937:+.pdf': No such file or directory
Warning: The inclusion levels of Event 'chrKI270897.1:295983:296093:+@chrKI270897.1:301862:301915:+@chrKI270897.1:302360:302501:          +' contains 'NA' value, which could lead to unexpected output.
<module 'misopy' from '/home/yijia/miniconda3/envs/rmats/lib/python2.7/site-packages/MISO/misopy/__init__.pyc'>
```
There were something wrong with my bam files, but I don't know how to figure them.

Any help would be greatly appreciated!

Sincerely,
Yijia

**Comment by YijiaChi** [comment]
gtf=Gencode/gencode.v43.chr_patch_hapl_scaff.annotation.gtf

nohup rmats.py --b1 b1.txt --b2 b2.txt --gtf $gtf --od results/1_2rmats --tmp results/1_2rmats.tmp --readLength 150 --variable-read-length --nthread20 &

`gencode.v43.chr_patch_hapl_scaff.annotation.gtf`:

```
##description: evidence-based annotation of the human genome (GRCh38), version 43 (Ensembl 109)
##provider: GENCODE
##contact: gencode-help@ebi.ac.uk
##format: gtf
##date: 2022-11-29
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000290825.1"; gene_type "lncRNA"; gene_name "DDX11L2"; level 2; tag "overlaps_pseudogene";
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    11869   12227   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    12613   12721   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
```

**Comment by EricKutschera** [comment]
rmats adds 'chr' to contig names in the output if they don't already start with 'chr'. I think the intention is to give consistent output despite some references naming chromosomes chr1, chr2, chr3, ... and other references naming them just 1, 2, 3, ...

This can cause an issue in rmats2sashimiplot in some cases. The latest rmats2sashimiplot code includes arguments to remove or keep the chr prefix:
https://github.com/Xinglab/rmats2sashimiplot#all-arguments
```
 --keep-event-chr-prefix
                       force the contig name in the provided events file to
                       be used
 --remove-event-chr-prefix
                       remove any leading "chr" from contig names in the
                       provided events file
```

The code also tries to automatically figure out whether to remove the chr prefix. In your case it looks like the automatic detection doesn't work because the reference does use chr1, but you're trying to plot for one of the contigs that doesn't start with chr (KI270897.1)

Here's a related issue
https://github.com/Xinglab/rmats2sashimiplot/issues/64

**Comment by YijiaChi** [comment]
Thanks for your detailed reply! It does help me solve my probelm !!
I have installed rmats2sashimiplot by `conda install rmats2sashimiplot ` without check the version, which does not includes arguments `--keep-event-chr-prefix` and ` --remove-event-chr-prefix`.

 After reinstalling the latest version rmats2sashimiplot with the code below and rerunning my script, I finally get the plots!
```
#python --version
#Python 3.9.13
 
git clone https://github.com/Xinglab/rmats2sashimiplot.git
cd rmats2sashimiplot/
pip uninstall rmats2sashimiplot
python ./setup.py install
rmats2sashimiplot

```
