### ISSUE TITLE
Test example data: No entries found for gene chr16:9000:25001:+ in GFF

### ISSUE THREAD

**Issue by yangchuhua** [Xinglab/rmats2sashimiplot#114]
To Whom It May Concern,

I downloaded the test data and ran as the example form BAM files, but I got the error: Loaded 0 genes. But the coordinate in GFF3 file locates in the regions in the example ` -c chr16:+:9000:25000`.

I wonder if you have any idea about this error. Do I need to do something for the GFF files?

```bash
$ rmats2sashimiplot --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam -c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3 --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o test_coordinate_output

'./rmats2sashimiplot_test_data/sample_1_replicate_1.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_1_replicate_1.bam.bai'
'./rmats2sashimiplot_test_data/sample_1_replicate_2.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_1_replicate_2.bam.bai'
'./rmats2sashimiplot_test_data/sample_1_replicate_3.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_1_replicate_3.bam.bai'
'./rmats2sashimiplot_test_data/sample_2_replicate_1.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_2_replicate_1.bam.bai'
'./rmats2sashimiplot_test_data/sample_2_replicate_2.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_2_replicate_2.bam.bai'
'./rmats2sashimiplot_test_data/sample_2_replicate_3.bam' seems to be indexed already. Please Check out this index file './rmats2sashimiplot_test_data/sample_2_replicate_3.bam.bai'

<module 'misopy' from './miniconda3/envs/sashimiplot_20231109/lib/python2.7/site-packages/MISO/misopy/__init__.pyc'>
Indexing GFF...
  - GFF: ./test_coordinate_output/Sashimi_index/tmp.gff3
  - Outputting to: ./test_coordinate_output/Sashimi_index
WARNING: No entries found for gene chr16:9000:25001:+ in GFF ./test_coordinate_output/Sashimi_index/tmp.gff3
Skipping gene chr16:9000:25001:+...
Loaded 0 genes
  - Loading of genes from GFF took 0.00 seconds
Outputting gene records in GFF format...
  - Output file: ./test_coordinate_output/Sashimi_index/genes.gff
  - Serialization of genes from GFF took 0.01 seconds
Indexing of GFF took 0.01 seconds.
./miniconda3/envs/sashimiplot_20231109/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "./miniconda3/envs/sashimiplot_20231109/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "./miniconda3/envs/sashimiplot_20231109/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "./miniconda3/envs/sashimiplot_20231109/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 148, in plot_event
    %(event_name, pickle_dir)
Exception: Event chr16:9000:25001:+ not found in pickled directory ./test_coordinate_output/Sashimi_index. Are you sure this is the right directory for the event?
mv: cannot stat ‘./test_coordinate_output/Sashimi_plot/chr16:9000:25001:+.pdf’: No such file or directory
```

<img width="1389" alt="image" src="https://github.com/Xinglab/rmats2sashimiplot/assets/26158915/1f945438-ebe4-4270-b0c6-991861fb0a4a">

**Comment by EricKutschera** [comment]
It looks like you may be running an older version of the code (v2.0.3 or earlier). The test data gff3 uses `transcript` as the feature name, but v2.0.3 and earlier require the feature to be `mRNA`: https://github.com/Xinglab/rmats2sashimiplot/pull/37

You could try installing the latest version, or you can run from the latest source code using `python /path/to/rmats2sashimiplot.py`:
```
git clone https://github.com/Xinglab/rmats2sashimiplot.git
python ./rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 ...
```
