### ISSUE TITLE
ValueError: 'chr' is not in list

### ISSUE THREAD

**Issue by Portulaca666** [Xinglab/rmats2sashimiplot#115]
Hi ，Thanks for the great rmats2sashimiplot~
(rmats2sashimiplot) [xjhuang_pkuhpc@login07 rmats2sashimiplot-master]# rmats2sashimiplot --b1 `cat /home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/sample_WT`  --b2 `cat /home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/sample_KO`   --l1 SampleWT --l2 SampleKO --event-type SE  -e ${output_paths}/grep_Fn1_SE.MATS.JC.txt  -o ${test_coordinate_output}
'/home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/2023-11-23-13_13_55_149906_bam1_1/Aligned.sortedByCoord.out.bam' is indexed already: '/home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/2023-11-23-13_13_55_149906_bam1_1/Aligned.sortedByCoord.out.bam.bai'
Indexing '/home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/2023-11-23-13_13_55_149906_bam2_1/Aligned.sortedByCoord.out.bam'.
Indexing '/home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/2023-11-23-13_13_55_149906_bam2_2/Aligned.sortedByCoord.out.bam'.

Indexing '/home/xjhuang_pkuhpc/gpfs1/help/LQQ/mouse/RNA_mouse/rMATs/NC_KO/tmp_output/2023-11-23-13_13_55_149906_bam2_3/Aligned.sortedByCoord.out.bam'.
'chr' is not in list
There is an exception in plot_with_eventsfile
Traceback (most recent call last):
  File "/home/xjhuang_pkuhpc/gpfs1/anaconda3/envs/mamba/envs/rmats2sashimiplot/bin/rmats2sashimiplot", line 33, in <module>
    sys.exit(load_entry_point('rmats2sashimiplot==3.0.0', 'console_scripts', 'rmats2sashimiplot')())
  File "/home/xjhuang_pkuhpc/gpfs1/anaconda3/envs/mamba/envs/rmats2sashimiplot/lib/python3.8/site-packages/rmats2sashimiplot-3.0.0-py3.8.egg/rmats2sashimiplot/rmats2sashimiplot.py", line 949, in main
    plot_with_eventsfile(options)
  File "/home/xjhuang_pkuhpc/gpfs1/anaconda3/envs/mamba/envs/rmats2sashimiplot/lib/python3.8/site-packages/rmats2sashimiplot-3.0.0-py3.8.egg/rmats2sashimiplot/rmats2sashimiplot.py", line 606, in plot_with_eventsfile
    options.events_file = create_chr_aware_events_file(options)
  File "/home/xjhuang_pkuhpc/gpfs1/anaconda3/envs/mamba/envs/rmats2sashimiplot/lib/python3.8/site-packages/rmats2sashimiplot-3.0.0-py3.8.egg/rmats2sashimiplot/rmats2sashimiplot.py", line 589, in create_chr_aware_events_file
    chr_index = columns.index('chr')
ValueError: 'chr' is not in list

I donot know what is this mean .

**Comment by EricKutschera** [comment]
This is the line for the error: https://github.com/Xinglab/rmats2sashimiplot/blob/v3.0.0/src/rmats2sashimiplot/rmats2sashimiplot.py#L589

It's reading the `-e` file (`${output_paths}/grep_Fn1_SE.MATS.JC.txt`) and it expects the first line to be the tab separated column names. Does the `-e` file have the original header line from the rmats output?

Here's a related post: https://github.com/Xinglab/rmats2sashimiplot/issues/72
