### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by lmanchon** [Xinglab/rmats2sashimiplot#12]
--Hello,

i don't know what's wrong:

rmats2sashimiplot --b1 SRR031760_61.bam --b2 SRR074428_29.bam -c 2L:+:11500000:11550000:Droso.gff3 --l1 B52_RNAi --l2 B52_control --exon_s 1 --intron_s 5 -o outDir

<module 'misopy' from 'sashimiplot/lib/python/rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/__init__.pyc'>
Indexing GFF...
  - GFF: outDir/Sashimi_index/tmp.gff3
  - Outputting to: outDir/Sashimi_index
ENST00000000000 has no exons
Through 0 genes...
Loaded 1 genes
  - Loading of genes from GFF took 0.00 seconds
Making directory: outDir/Sashimi_index/chr2L
  - Chromosome serialization took 0.00 seconds
Outputting gene records in GFF format...
  - Output file: outDir/Sashimi_index/genes.gff
  - Serialization of genes from GFF took 0.04 seconds
Indexing of GFF took 0.04 seconds.
Traceback (most recent call last):
  File "rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 285, in <module>
    main()
  File "rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 281, in main
    plot_label=plot_label)
  File "rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 158, in plot_event
    plot_label=plot_label)
  File "rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 680, in plot_density_from_file
    parseGene(pickle_filename, event)
  File "rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/parse_gene.py", line 48, in parseGene
    mRNAs, strand, chrom
UnboundLocalError: local variable 'strand' referenced before assignment
mv: cannot stat `outDir/Sashimi_plot/chr2L:11500000:11550001:+.pdf': No such file or directory

**Comment by dm-druid** [comment]
It is possible that if the `event` could not match the `gene_id`, then the strand doesn't get a value. 
![1](https://cloud.githubusercontent.com/assets/15811449/26022205/1073b638-37d1-11e7-9686-07c2f45f683f.png)
This is the part of the code about that. There may be some problem with your data, but it is hard to find where the problem is. So could you share your date with us to help find the problem. Thanks.
