### ISSUE TITLE
Error when running on rMATS generated BAM files

### ISSUE THREAD

**Issue by nicholas-moskwa** [Xinglab/rmats2sashimiplot#139]
Hi,

I am trying to generate sashimi plots using BAM files made from running rMATS on FASTQ files. I am using two files that hold my replicates.

My run:
python /Packages/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 10_129S.txt --b2 10_B6.txt -c chr7:+:27256438:27284145:/genomes/mm10/gencode.vM36.annotation.gff3 --l1 129S --l2 B6 --exon_s 1 --intron_s 5 -o ${dir_out}

My error:
 File "/Packages/rmats2sashimiplot/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
  File "/Packages/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
'/mm10-tmp/2024-02-01-13_40_35_331660_bam1_1/Aligned.sortedByCoord.out.bam' is indexed already: '/mm10-tmp/2024-02-01-13_40_35_331660_bam1_1/Aligned.sortedByCoord.out.bam.bai'
'mm10-tmp/2024-02-01-13_40_35_331660_bam2_1/Aligned.sortedByCoord.out.bam' is indexed already: '/mm10-tmp/2024-02-01-13_40_35_331660_bam2_1/Aligned.sortedByCoord.out.bam.bai'

Thanks for your help!

**Comment by EricKutschera** [comment]
Here's a similar issue: https://github.com/Xinglab/rmats2sashimiplot/issues/138#issuecomment-2454752015

You could try:
```
cd /Packages/rmats2sashimiplot
./2to3.sh
```

**Comment by nicholas-moskwa** [comment]
Okay, that changed the error, I think most of the script ran, but now I see this error:
Error retrieving files from chr7: invalid contig `chr7`
Are you sure chr7 appears in your BAM file?

I am using rMATS output BAM files, how does rMATS assign configs?

**Comment by EricKutschera** [comment]
That error can happen if you use the same `-o` directory for multiple runs. The code will see files from a previous run (which may have had an error) and the old files can cause the error: https://github.com/Xinglab/rmats2sashimiplot/issues/92#issuecomment-1446841032

**Comment by nicholas-moskwa** [comment]
I deleted the output directory and re-ran my scripts and saw this, should I use a gene name instead of a coordinate: 

<module 'misopy' from '/pod/2/ch-lee-lab/labdata/Packages/rmats2sashimiplot/src/MISO/misopy/__init__.py'>
Indexing GFF...
  - GFF: /10_Rmats2sashimiplot/Sashimi_index/tmp.gff3
  - Outputting to: /10_Rmats2sashimiplot/Sashimi_index
WARNING: No entries found for gene 7_27256438_27284146_+ in GFF /10_Rmats2sashimiplot/Sashimi_index/tmp.gff3
Skipping gene 7_27256438_27284146_+...
Loaded 0 genes
  - Loading of genes from GFF took 0.00 seconds
Outputting gene records in GFF format...
  - Output file: /10_Rmats2sashimiplot/Sashimi_index/genes.gff
  - Serialization of genes from GFF took 0.03 seconds
Indexing of GFF took 0.04 seconds.
Traceback (most recent call last):
  File "/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 148, in plot_event
    %(event_name, pickle_dir))
Exception: Event 7_27256438_27284146_+ not found in pickled directory /10_Rmats2sashimiplot/Sashimi_index. Are you sure this is the right directory for the event?

**Comment by EricKutschera** [comment]
The issue might be that your bam files don't have `chr` but you're using a gff3 that does. It looks like you have `gencode.vM36.annotation.gff3` which has `chr7` and the error is about an event on just `7` which would be based on the coordinates from the `-c` argument. I think you could remove the `chr` prefix from your gff3 with:
```
sed s/^chr// gencode.vM36.annotation.gff3 > gencode.vM36.annotation_no_chr.gff3
```

Then you could use that updated gff3 file
