### ISSUE TITLE
important imformation 

### ISSUE THREAD

**Issue by millersan** [Xinglab/rmats2sashimiplot#28]
If you find your sashimiplot can't run , you may check the Error as well as to find out which packages  you haven't installed. 
If you find your sashimiplot can run , but can not get the plot . You may check your rmats-result . In the chr colon , try to replace the chr to blank. Because in the bam file, there is no chr label on chromosome. 
Try to run again , you will get your plot .
Good luck.

**Comment by thereallda** [comment]
Hi millersan!

I have encountered the issue that **'my sashimiplot can run, but I can not get my plot'**. Also, I have tried your solution metioned here(replace the "chr" to blank in rmats-result), but I still get the following error when I tried to plot:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 148, in plot_event
    %(event_name, pickle_dir)
Exception: Event    1:13682084:13682276:+@   1:13687063:13687194:+@   1:13696687:13699956:+ not found in pickled directory /public/home/zhaojing/lda_tmp/tmp/SE_plot/Sashimi_index_Nhsl1_1. Are you sure this is the right directory for the event?`

In addition, when I just simply use the unmodifed rmats-result, I still can not get the plot, it return error like this:
`Error retrieving files from chr1: invalid contig `chr1`
Are you sure chr1 appears in your BAM file?
Aborting plot...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 392, in plot_density
    junction_log_base=junction_log_base)`

So I wonder which steps I misunderstand your meaning, and how can I plot it.

Thanks,
Dean

**Comment by millersan** [comment]
Hi, Dean, 

 My suggestion is that put all file in&nbsp;one operation environment, and use my advice in github. Here is my code to run the sashimiplot.
 &nbsp;
 for i in {A3SS,A5SS,MXE,RI,SE};do rmats2sashimiplot 
 --b1 Ctrl1.HISAT_aln.sorted.bam,Ctrl2.HISAT_aln.sorted.bam,Ctrl3.HISAT_aln.sorted.bam 
 --b2 L02a.HISAT_aln.sorted.bam,L02b.HISAT_aln.sorted.bam,L02c.HISAT_aln.sorted.bam 
 -t ${i} -e ./Allplot/A0vsA2/${i}/${i}.MATS.JCEC.txt 
 --l1 0h --l2 2h --min-counts 0&nbsp;
 --exon_s 1 --intron_s 1 
 -o ./Allplot/A0vsA2/${i};&nbsp;&nbsp; 
 done
 
&nbsp;
 Hope these points could help you.
 &nbsp;
 Sincerely, millersan





 &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dean Li"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 晚上9:20
收件人: "Xinglab/rmats2sashimiplot"<rmats2sashimiplot@noreply.github.com&gt;; 
抄送: "Imagine."<349927235@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Xinglab/rmats2sashimiplot] important imformation  (#28)




Hi millersan!
 
I have encountered the issue that 'my sashimiplot can run, but I can not get my plot'. Also, I have tried your solution metioned here(replace the "chr" to blank in rmats-result), but I still get the following error when I tried to plot:
 
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module&gt; main() File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main plot_label=plot_label) File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 148, in plot_event %(event_name, pickle_dir) Exception: Event 1:13682084:13682276:+@ 1:13687063:13687194:+@ 1:13696687:13699956:+ not found in pickled directory /public/home/zhaojing/lda_tmp/tmp/SE_plot/Sashimi_index_Nhsl1_1. Are you sure this is the right directory for the event?
 
In addition, when I just simply use the unmodifed rmats-result, I still can not get the plot, it return error like this:
Error retrieving files from chr1: invalid contig chr1 Are you sure chr1 appears in your BAM file? Aborting plot... Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module&gt; main() File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main plot_label=plot_label) File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in plot_event plot_label=plot_label) File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file plot_title=plot_title) File "/usr/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 392, in plot_density junction_log_base=junction_log_base)
 
So I wonder which steps I misunderstand your meaning, and how can I plot it.
 
Thanks,
Dean

**Comment by thereallda** [comment]
Thanks for your reply! @millersan

I did put all the file in one directory but failed to plot. Here is my code:

```
rmats2sashimiplot --b1 1.sorted.bam,2.sorted.bam,3.sorted.bam,4.sorted.bam\
 --b2 5.sorted.bam,6.sorted.bam,7.sorted.bam,8.sorted.bam\
 -t SE -e ./SE.sorted10.txt --l1 control --l2 sh1 -o SE_plot
```

And here is my modified rmats-results:

```
ID	GeneID	geneSymbol	chr	strand ...
0	"ENSRNOG00000014637"	"Atxn10"	   7	+ ...
...
``` 

Thanks 
Dean

**Comment by thereallda** [comment]
I successfully get the plot by simply deleting the "chr" in rmats-restults instead of replacing it to blank. Here is the plot:

![image](https://user-images.githubusercontent.com/55836943/69909335-005ae300-1435-11ea-9860-61f17cf1fad0.png)

The point is to creat this "{chromosome number}:{exon start}:{exon end}" format, for example "1:13682084:13682276", which can be recognized by sashimiplot and be compatible with bam.file

Thanks for @millersan kindest help , appreciate it!

**Comment by millersan** [comment]
Congratulations on the success of your experiment! You get my point!
(๑•̀ㅂ•́)و✧

**Comment by EricKutschera** [comment]
The "Are you sure chr1 appears in your BAM file?" issue was addressed in https://github.com/Xinglab/rmats2sashimiplot/pull/36
