### ISSUE TITLE
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by feedmewifi** [Xinglab/rmats2sashimiplot#35]
my command is:
`rmats2sashimiplot --b1 /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080197.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080198.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080199.Aligned.sortedByCoord.out.bam --b2 /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080203.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080204.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080205.Aligned.sortedByCoord.out.bam -t A3SS -c chr3:+:60472830:60629750:/orange/swanson/carter.h/genomes/mouse/ensembl/Mus_musculus.GRCm38.100.gff3 -e /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/fastq_files/GSM4080197-99_203-205/fromGTF.novelSpliceSite.A3SS.txt --l1 wt --l2 480/480 -o /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/fastq_files/GSM4080197-202`

stdout:
```
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080197.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080198.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080199.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080203.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080204.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Indexing '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080205.Aligned.sortedByCoord.out.bam'.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

A3SS: ['5902', '"ENSMUSG00000059326"', '"Csf2ra"', 'chr19', '-', '61225132', '61225214', '61225132', '61225176', '61225323', '61225490\n']
Traceback (most recent call last):
  File "/apps/rmats2sashimiplot/2.0.3/bin/rmats2sashimiplot", line 10, in <module>
    sys.exit(main())
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 785, in main
    plot_with_eventsfile(options)
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 503, in plot_with_eventsfile
    coor = EventCoor(options.event_type, items)
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 431, in __init__
    self.inc_level1 = items[20]  # IncLevel1
IndexError: list index out of range

```

**Comment by feedmewifi** [comment]
I have gone in and indexed the bam files by hand, and I'm still getting an error:
command:
`rmats2sashimiplot --b1 /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080197.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080198.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080199.Aligned.sortedByCoord.out.bam --b2 /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080203.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080204.Aligned.sortedByCoord.out.bam,/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080205.Aligned.sortedByCoord.out.bam -t A3SS -c chr3:+:60472830:60629750:/orange/swanson/carter.h/genomes/mouse/ensembl/Mus_musculus.GRCm38.100.gff3 -e /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/fastq_files/GSM4080197-99_203-205/fromGTF.novelSpliceSite.A3SS.txt --l1 wt --l2 480/480 -o /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/fastq_files/GSM4080197-202`

output:
```
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080197.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080197.Aligned.sortedByCoord.out.bam.bai'
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080198.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080198.Aligned.sortedByCoord.out.bam.bai'
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080199.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080199.Aligned.sortedByCoord.out.bam.bai'
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080203.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080203.Aligned.sortedByCoord.out.bam.bai'
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080204.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080204.Aligned.sortedByCoord.out.bam.bai'
'/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080205.Aligned.sortedByCoord.out.bam' seems to be indexed already. Please Check out this index file '/orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/STAR_output/GSM4080205.Aligned.sortedByCoord.out.bam.bai'

A3SS: ['5902', '"ENSMUSG00000059326"', '"Csf2ra"', 'chr19', '-', '61225132', '61225214', '61225132', '61225176', '61225323', '61225490\n']
Traceback (most recent call last):
  File "/apps/rmats2sashimiplot/2.0.3/bin/rmats2sashimiplot", line 10, in <module>
    sys.exit(main())
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 785, in main
    plot_with_eventsfile(options)
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 503, in plot_with_eventsfile
    coor = EventCoor(options.event_type, items)
  File "/apps/rmats2sashimiplot/2.0.3/lib/python2.7/site-packages/rmats2sashimiplot/rmats2sashimiplot.py", line 431, in __init__
    self.inc_level1 = items[20]  # IncLevel1
IndexError: list index out of range

```

**Comment by Lix1993** [comment]
modify you ~/.condarc
```cat ~/.condarc 
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by Lix1993** [comment]
if not works, reinstall conda may help

**Comment by EricKutschera** [comment]
The initial error about loading libcrypto seems to be an issue with your samtools install and not rmats2sashimiplot

The "list index out of range" error is because of the `-e` value. You are using `-e /orange/swanson/carter.h/ChP_Splicing_Project/Dmpk_KI_Mice/fastq_files/GSM4080197-99_203-205/fromGTF.novelSpliceSite.A3SS.txt` which is a "fromGTF" file, but a "MATS" file is needed. You may want A3SS.MATS.JC.txt

Also you are using `-t`, `-e`, and `-c`. You should use either (`-t` and `-e`) or (`-c`)
