### ISSUE TITLE
IndexError: index out of bounds

### ISSUE THREAD

**Issue by shum-sky** [Xinglab/rmats2sashimiplot#50]
Hi and Merry Christmas!

I faced a problem with rmats2sashimi plot. When trying to make a plot using the -c option, the following error appears. However, it appears on some, but not all coordinates, using the same command with different coordinates can produce a plot.

Command (filenames omitted): 
`python2 /home/ashumskiy/Programs/rmats2sashimiplot/build/lib/rmats2sashimiplot/rmats2sashimiplot.py --b1 files --b2 files -c chr7:+:28815279:28818532:/home/ashumskiy/Mus_musculus.GRCm38.100.gtf --l1 WTND --l2 KOND --exon_s 1 --intron_s 5 -o /home/ashumskiy/SIRT6/rMATS/output_dima/sashimi/test_output`

Here is the error:

Traceback (most recent call last):
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/sashim                                 i_plot.py", line 293, in <module>
    main()
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/sashim                                 i_plot.py", line 289, in main
    plot_label=plot_label)
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/sashim                                 i_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/plot_u                                 tils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/plot_u                                 tils/plot_gene.py", line 495, in plot_density
    plot_mRNAs(tx_start, mRNAs, strand, graphcoords, reverse_minus)
  File "/home/ashumskiy/Programs/rmats2sashimiplot/build/lib/MISO/misopy/sashimi_plot/plot_u                                 tils/plot_gene.py", line 643, in plot_mRNAs
    x = [graphcoords[s], graphcoords[e], graphcoords[e], graphcoords[s]]
IndexError: index out of bounds

**Comment by EricKutschera** [comment]
I think the issue is that a gff3 is needed instead of a gtf. I was able to reproduce that stack trace using ftp://ftp.ensembl.org/pub/release-100/gtf/mus_musculus/Mus_musculus.GRCm38.100.gtf.gz

I was able to produce a plot after I converted to a gff3 with https://anaconda.org/bioconda/gffread: `gffread --keep-genes ./Mus_musculus.GRCm38.100.gtf -o ./Mus_musculus.GRCm38.100.gff3`

**Comment by shum-sky** [comment]
Eric, it seems to have worked, thanks!
