### ISSUE TITLE
can‘t find pdf files

### ISSUE THREAD

**Issue by haiyun-fan** [Xinglab/rmats2sashimiplot#61]
**errors**：
 pickled_file = file(pickled_filename, 'w')
IOError: [Errno 22] invalid mode ('w') or filename: '/media/user/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_index_NA_3018/chrSc08/chrSc08:9528323:9528403:+@chrSc08:9528736:9528797:+@chrSc08:9528994:9529075:+.pickle'
python /home/user/miniconda3/envs/rmats2sashimiplot/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "chrSc08:9528323:9528403:+@chrSc08:9528736:9528797:+@chrSc08:9528994:9529075:+" /media/fhy/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_index_NA_3018 /media/fhy/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_index_NA_3018/sashimi_plot_settings.txt --output-dir /media/fhy/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_plot
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/rmats2sashimiplot/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/home/user/miniconda3/envs/rmats2sashimiplot/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/home/user/miniconda3/envs/rmats2sashimiplot/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 142, in plot_event
    %(genes_filename)
Exception: Cannot find file /media/user/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_index_NA_3018/genes_to_filenames.shelve. Are you sure the events were indexed with the latest version of index_gff.py?
mv:  Library not loaded/SE_plot/Sashimi_plot
/chrSc08:9528323:9528403:+@chrSc08:9528736:9528797:+@chrSc08:9528994:9529075:+.pdf':No such file or directory"
Warning: The inclusion levels of Event 'chrSc08:15995698:15995819:+@chrSc08:15995945:15996076:+@chrSc08:15996202:15996445:+' contains 'NA' value, which could lead to unexpected output.
<module 'misopy' from '/home/user/miniconda3/envs/rmats2sashimiplot/lib/python2.7/site-packages/MISO/misopy/__init__.pyc'>

**then** 
Reinstall like this：
conda create --prefix ./new_conda_env
conda activate ./new_conda_env/
conda install -c conda-forge -c bioconda python=2 numpy scipy matplotlib pysam samtools bedtools
conda install -c bioconda rmats2sashimiplot
The same error occurred after running the command.
Please advise. thankyou！

**Comment by EricKutschera** [comment]
For the first error:
`IOError: [Errno 22] invalid mode ('w') or filename: '/media/user/0A9AD66165F33762/SAN/Splicing/01-hisat2/SE_plot/Sashimi_index_NA_3018/chrSc08/chrSc08:9528323:9528403:+@chrSc08:9528736:9528797:+@chrSc08:9528994:9529075:+.pickle'`

My guess is that one of the characters in the file name (like `:`) is not valid for your filesystem. Are you able to create a file with that name on the command line with: `touch 'chrSc08:9528323:9528403:+@chrSc08:9528736:9528797:+@chrSc08:9528994:9529075:+.pickle'`

You can show the filesystem types on your system with `df -T`

**Comment by pangxueyu233** [comment]
Hi, 
I just met the same problem that cannot find the pdf files, @EricKutschera 
could you help me how to avoid generate the prefix names without strange symbols? 
here is my codes:
~~~R
python ./programme/rmats2sashimiplot-master/src/rmats2sashimiplot/rmats2sashimiplot.py \
--b1 ./N1.Aligned.sortedByCoord.out.bam,./N2.Aligned.sortedByCoord.out.bam,./N3.Aligned.sortedByCoord.out.bam \
--b2 ./P1.Aligned.sortedByCoord.out.bam,./P2.Aligned.sortedByCoord.out.bam,./P3.Aligned.sortedByCoord.out.bam,./P4.Aligned.sortedByCoord.out.bam,./P5.Aligned.sortedByCoord.out.bam,./P6.Aligned.sortedByCoord.out.bam,./P7.Aligned.sortedByCoord.out.bam,./P8.Aligned.sortedByCoord.out.bam \
-t SE \
-e ./AS_output/AML_VS_NOR/DNMT3B.SE.MATS.JC.txt \
--l1 Nor --l2 AML \
--exon_s 1 \
--intron_s 5 \
-o DNMT3B.SE_events_output \
--remove-event-chr-prefix
~~~
And I got the errors like these:
~~~R
Warning: The inclusion levels of Event '20_31372564_31372665_+@20_31374308_31374433_+@20_31375036_31375257_+' contains 'NA' value, which could lead to unexpected output.
  File "/mnt/data/user_data/xiangyu/programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31372564_31372665_+@20_31374308_31374433_+@20_31375036_31375257_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_1 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_1/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31372564_31372665_+@20_31374308_31374433_+@20_31375036_31375257_+.pdf': No such file or directory
Warning: The inclusion levels of Event '20_31375036_31375257_+@20_31376660_31376818_+@20_31379407_31379514_+' contains 'NA' value, which could lead to unexpected output.
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31375036_31375257_+@20_31376660_31376818_+@20_31379407_31379514_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_2 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_2/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31375036_31375257_+@20_31376660_31376818_+@20_31379407_31379514_+.pdf': No such file or directory
Warning: The inclusion levels of Event '20_31376660_31376818_+@20_31379407_31379514_+@20_31383215_31383340_+' contains 'NA' value, which could lead to unexpected output.
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31376660_31376818_+@20_31379407_31379514_+@20_31383215_31383340_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_3 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_3/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31376660_31376818_+@20_31379407_31379514_+@20_31383215_31383340_+.pdf': No such file or directory
Warning: The inclusion levels of Event '20_31379407_31379514_+@20_31380432_31380576_+@20_31383215_31383340_+' contains 'NA' value, which could lead to unexpected output.
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31379407_31379514_+@20_31380432_31380576_+@20_31383215_31383340_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_4 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_4/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31379407_31379514_+@20_31380432_31380576_+@20_31383215_31383340_+.pdf': No such file or directory
Warning: The inclusion levels of Event '20_31390191_31390276_+@20_31394015_31394133_+@20_31395568_31397162_+' contains 'NA' value, which could lead to unexpected output.
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31390191_31390276_+@20_31394015_31394133_+@20_31395568_31397162_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_5 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_5/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31390191_31390276_+@20_31394015_31394133_+@20_31395568_31397162_+.pdf': No such file or directory
Warning: The inclusion levels of Event '20_31393144_31393213_+@20_31394015_31394133_+@20_31395568_31397162_+' contains 'NA' value, which could lead to unexpected output.
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
/usr/bin/python ./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "20_31393144_31393213_+@20_31394015_31394133_+@20_31395568_31397162_+" ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_6 ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_index_DNMT3B_6/sashimi_plot_settings.txt --output-dir ./workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot
  File "./programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
mv: cannot stat './workshop/AS_AML/OUR_AML_DATA/AS_output/AML_VS_NOR/DNMT3B.SE_events_output/Sashimi_plot/20_31393144_31393213_+@20_31394015_31394133_+@20_31395568_31397162_+.pdf': No such file or directory
~~~

**Comment by pangxueyu233** [comment]
And I tried the testdata with the codes in documents, it still report errors:
here is my codes and report:
~~~R
python ./src/rmats2sashimiplot/rmats2sashimiplot.py \
> --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam \
> --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam \
> -c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3 \
> --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 \
> -o test_coordinate_output


'./rmats2sashimiplot_test_data/sample_1_replicate_1.bam' is indexed already: './rmats2sashimiplot_test_data/sample_1_replicate_1.bam.bai'
'./rmats2sashimiplot_test_data/sample_2_replicate_1.bam' is indexed already: './rmats2sashimiplot_test_data/sample_2_replicate_1.bam.bai'
  File "/mnt/data/user_data/xiangyu/programme/rmats2sashimiplot-master/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
                               ^
SyntaxError: invalid syntax
  File "/mnt/data/user_data/xiangyu/programme/rmats2sashimiplot-master/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: %s does not end in .miso_bf, are you sure it is the " \)?
~~~

**Comment by EricKutschera** [comment]
The syntax errors are from running python2 code with a python3 interpreter

You can see the path and version of the python interpreter you are using with:
```
which python
python --version
```

If you can switch to a python2 interpreter that should resolve the syntax errors

It looks like you are running directly from the github source code so another option is to run https://github.com/Xinglab/rmats2sashimiplot/blob/master/2to3.sh. That will convert the code to python3 so it should work with your python3 interpreter

**Comment by pangxueyu233** [comment]
Yeah, I work it out after running the 2to3.sh.
Thanks for your immediately reply
