### ISSUE TITLE
Large number of samples not supported?

### ISSUE THREAD

**Issue by OnkarMulay** [Xinglab/rmats2sashimiplot#73]
**The number of custom colors is 51 which doesn't match the group number 2. The program uses the rainbow color as default.**
---------------
Reading sample label: KIAA1191 group1name IncLevel: 0.94
Traceback (most recent call last):
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 392, in plot_density
    junction_log_base=junction_log_base)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 75, in plot_density_single
    p1 = subprocess.Popen(["samtools", "idxstats", file_name,], stdout=subprocess.PIPE)
  File "/apps/python2/2.7.17/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/apps/python2/2.7.17/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
mv: cannot stat '/g/data/zq45/onkar/test_grouped_output/Sashimi_plot/5_175786814_175786921_-@5_175786484_175786570_-@5_175782574_175782752_-.pdf': No such file or directory

----------------
Doesn't it support large number of samples? Do I need to change anything for plotting? As exactly just before plotting step it has issues, otherwise all files are getting created before this step.

Thanks

**Comment by OnkarMulay** [comment]
Thanks Eric.
You are very helpful

module load samtools fixed it
