### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam'

### ISSUE THREAD

**Issue by CarrieBishop** [Xinglab/rmats2sashimiplot#96]
Thanks for you developing the rmats2sashimiplot-2.0.4, and I found some problems when I used the rmats2sashimiplot-2.0.4.
My command:
` python ./src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_01.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_02.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_03.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_06.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_08.bam --b2 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_01.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_02.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_03.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_06.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_08.bam -event-type A3SS -e /line/WJ/project/NY_Transcriptome2Genome/rMATS/output/DT_8vs16/A3SS.MATS.JC.txt -o /line/WJ/project/NY_Transcriptome2Genome/rMATS/rmats2sashimiplot/DT_8vs16/A3SS --l1 DT_8 --l2 DT_16 --exon_s 1 --intron_s 5 --min-counts 0
`
Here are my blogs:
```
Traceback (most recent call last):
  File "/home/LINE/local/app/rmats2sashimiplot-2.0.4/./src/rmats2sashimiplot/rmats2sashimiplot.py", line 7, in <module>
    import pysam
ModuleNotFoundError: No module named 'pysam'
```
I'm sure that I have download the pysam, but the program cannot run properly. Can you tell me how to correct my command and solve the problem?

**Comment by EricKutschera** [comment]
How did you install pysam? Are you able to import it if you just run `python` interactively:
```
python
>>> import pysam
```

You could try: `pip install pysam`

**Comment by CarrieBishop** [comment]
Thanks for your reply. I have installed the pysam and try what you said. I executed the command:
```
python
>>> import pysam
```
All my operation was though Xshell. If I ran under root privileges, the pysam can be called. But if I ran the command by my account number, the outcome was similar to what I have mentioned before. Here are my blogs:
```
(base) python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'
```
I tried to reinstall the pysam but failed:
```
pip install pysam
Collecting pysam
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /home/WJ/miniconda3/compiler_compat
      # pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -DNDEBUG  -O2 -Wall    -fPIC   -O2   -isystem /home/WJ/miniconda3/include -I/home/WJ/miniconda3/include    -fPIC   -O2   -isystem /home/WJ/miniconda3/include  -fPIC
      # pysam: (sysconfig) LDFLAGS=-Wl,-rpath,/home/WJ/miniconda3/lib -Wl,-rpath-link,/home/WJ/miniconda3/lib -L/home/WJ/miniconda3/lib -L/home/WJ/miniconda3/lib -Wl,-rpath,/home/WJ/miniconda3/lib -Wl,-rpath-link,/home/WJ/miniconda3/lib -L/home/WJ/miniconda3/lib
      checking for gcc... gcc -pthread -B /home/WJ/miniconda3/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /home/WJ/miniconda3/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /home/WJ/miniconda3/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      configure: Default CFLAGS_ARM/X86: -Wno-unused-result -Wsign-compare -DNDEBUG  -O2 -Wall    -fPIC   -O2   -isystem /home/WJ/miniconda3/include -I/home/WJ/miniconda3/include    -fPIC   -O2   -isystem /home/WJ/miniconda3/include  -fPIC
      checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... yes
      checking whether C compiler accepts -mavx2... yes
      checking whether C compiler accepts -mavx512f... no
      checking whether C compiler supports ARM Neon... no
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking how to run the C preprocessor... gcc -pthread -B /home/WJ/miniconda3/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... no
      configure: error: liblzma development files not found
      
      The CRAM format may use LZMA2 compression, which is implemented in HTSlib
      by using compression routines from liblzma <http://tukaani.org/xz/>.
      
      Building HTSlib requires liblzma development files to be installed on the
      build machine; you may need to ensure a package such as liblzma-dev (on Debian
      or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
      xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
      
      Either configure with --disable-lzma (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      checking for gcc... gcc -pthread -B /home/WJ/miniconda3/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /home/WJ/miniconda3/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /home/WJ/miniconda3/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      configure: Default CFLAGS_ARM/X86: -Wno-unused-result -Wsign-compare -DNDEBUG  -O2 -Wall    -fPIC   -O2   -isystem /home/WJ/miniconda3/include -I/home/WJ/miniconda3/include    -fPIC   -O2   -isystem /home/WJ/miniconda3/include  -fPIC
      checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... yes
      checking whether C compiler accepts -mavx2... yes
      checking whether C compiler accepts -mavx512f... no
      checking whether C compiler supports ARM Neon... no
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking how to run the C preprocessor... gcc -pthread -B /home/WJ/miniconda3/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... no
      configure: error: liblzma development files not found
      
      The CRAM format may use LZMA2 compression, which is implemented in HTSlib
      by using compression routines from liblzma <http://tukaani.org/xz/>.
      
      Building HTSlib requires liblzma development files to be installed on the
      build machine; you may need to ensure a package such as liblzma-dev (on Debian
      or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
      xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
      
      Either configure with --disable-lzma (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      Makefile:137: htscodecs.mk: No such file or directory
      config.mk:2: *** Resolve configure error first.  Stop.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "/home/WJ/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/WJ/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/WJ/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rouc1xuf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-rouc1xuf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rouc1xuf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-rouc1xuf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 383, in <module>
        File "<string>", line 79, in run_make_print_config
        File "/home/WJ/miniconda3/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/WJ/miniconda3/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I'm not sure if my Linux Workstation has wrong. Or I should reinstall the pysam. Can you tell me what I could do? I would appreciate it if you can help me solve the problem.

**Comment by EricKutschera** [comment]
It looks like this is the error:
```
Building HTSlib requires liblzma development files to be installed on the
build machine; you may need to ensure a package such as liblzma-dev (on Debian
or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
xz (via Homebrew on macOS) is installed; or build XZ Utils from source
```

You could try installing liblzma-dev or xz-devel based on that error message and trying the pip install again

It looks like you are using a conda environment so another option would be to try to install pysam with conda:
`conda install -c conda-forge -c bioconda pysam`

**Comment by CarrieBishop** [comment]
Thanks for your advise. I have solved the problem by the command `conda deactivate`. It seemed that the environment has conflict with pysam.When I ran the command again, I found something wrong. My command:
` python ./src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_01.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_02.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_03.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_06.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_08.bam --b2 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_01.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_02.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_03.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_06.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_08.bam -t SE -e /line/WJ/project/NY_Transcriptome2Genome/rMATS/output/DT_8vs16/SE.MATS.JC.txt -o /line/WJ/project/NY_Transcriptome2Genome/rMATS/rmats2sashimiplot/DT_8vs16/SE --l1 DT_8 --l2 DT_16 --exon_s 1 --intron_s 5 --min-counts 0`
The blog:
```
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_01.bam'.
[E::hts_idx_push] Unsorted positions on sequence #300: 11648312 followed by 11647089
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:11668:1031' with ref_name='ctg006680', ref_length=16293111, flags=163, pos=11647089 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_01.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_02.bam'.
[E::hts_idx_push] NO_COOR reads not in a single block at the end 53 -1
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:11415:1000' with ref_name='ctg006580', ref_length=31549, flags=99, pos=14632 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_02.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_03.bam'.
[E::hts_idx_push] Unsorted positions on sequence #32: 24079375 followed by 24079207
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:14163:1000' with ref_name='ctg002390', ref_length=30575023, flags=163, pos=24079207 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_03.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_06.bam'.
[E::hts_idx_push] NO_COOR reads not in a single block at the end 253 -1
[E::sam_index] Read 'A00403:687:HHC2CDSX2:2:1101:29234:1078' with ref_name='ctg001100', ref_length=12825986, flags=137, pos=6486923 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_06.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_08.bam'.
[E::hts_idx_push] Unsorted positions on sequence #113: 25266184 followed by 25266006
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:10330:1000' with ref_name='ctg002700', ref_length=45730232, flags=163, pos=25266006 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_08.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_01.bam'.
[E::hts_idx_push] Chromosome blocks not continuous
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:14154:1016' with ref_name='ctg002700', ref_length=45730232, flags=99, pos=22536644 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_01.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_02.bam'.
[E::hts_idx_push] Unsorted positions on sequence #300: 4089719 followed by 4089121
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:8721:1000' with ref_name='ctg006680', ref_length=16293111, flags=163, pos=4089121 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_02.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_03.bam'.
[E::hts_idx_push] NO_COOR reads not in a single block at the end 31 -1
[E::sam_index] Read 'A01040:138:HHHJVDSX2:2:1101:23737:1110' with ref_name='ctg002390', ref_length=30575023, flags=99, pos=3898044 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_03.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_06.bam'.
[E::hts_idx_push] Unsorted positions on sequence #56: 17394186 followed by 17368977
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:9769:1000' with ref_name='ctg006770', ref_length=31978632, flags=355, pos=17368977 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_06.bam"
Indexing '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_08.bam'.
[E::hts_idx_push] Unsorted positions on sequence #68: 3796155 followed by 3796079
[E::sam_index] Read 'A00838:577:HHJ7WDSX2:2:1101:15700:1000' with ref_name='ctg000290', ref_length=4094108, flags=163, pos=3796079 cannot be indexed
samtools index: failed to create index for "/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_16_08.bam"
[E::idx_find_and_load] Could not retrieve index file for '/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/DT_8_01.bam'
'>' not supported between instances of 'int' and 'str'
There is an exception in preparing coordinate setting file
'>' not supported between instances of 'int' and 'str'
There is an exception in plot_with_eventsfile
Traceback (most recent call last):
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 881, in <module>
    main()
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 877, in main
    plot_with_eventsfile(options)
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 746, in plot_with_eventsfile
    conf_setting_file(options, gene_no_str, gene_symbol, events_name_level, coor.id_str)
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 183, in conf_setting_file
    setting["min_counts"] = max(options.min_counts, 0)
TypeError: '>' not supported between instances of 'int' and 'str'
```
I'm sure I have eastablished an index by samtools. The` SE.MATS.JC.txt` was from rMATS and has no change. I would appreciate it if you could give me any advice.
Thanks!

**Comment by EricKutschera** [comment]
It looks like there are two different errors. For the samtools index error, the input bam files need to be sorted. You should be able to run: `samtools sort -o /path/for/sorted_output.bam /path/to/input.bam`. And then use the sorted bam files as input in your rmats2sashimiplot command

The other error happens when parsing the --min-counts argument. Since you are using `--min-counts 0` and 0 is the default you could just remove that from your command to avoid the error

There is also a fix for that error in the latest master branch: https://github.com/Xinglab/rmats2sashimiplot/pull/93

**Comment by CarrieBishop** [comment]
I used the  sorted bam files as input as you said. My command:
`python ./src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_8_01.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_8_02.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_8_03.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_8_06.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_8_08.sorted.bam --b2 /line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_16_01.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_16_02.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_16_03.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_16_06.sorted.bam,/line/WJ/project/NY_Transcriptome2Genome/04_samtools_SNPcalling/sort/DT_16_08.sorted.bam -t SE -e /line/WJ/project/NY_Transcriptome2Genome/rMATS/output/DT_8vs16/SE.MATS.JC.txt -o /line/WJ/project/NY_Transcriptome2Genome/rMATS/rmats2sashimiplot/DT_8vs16/SE --l1 DT_8 --l2 DT_16 --exon_s 1 --intron_s 5`
I have encountered the problem similar to the #94 ,and I tried used older matplotlib version. The matplotlib version is 3.3.4 and I can't install the matplotlib3.4.3:
![{A_T3~XM4{U YV5KZRPP3TS](https://github.com/Xinglab/rmats2sashimiplot/assets/133024702/41a28e57-8607-4a47-b94f-41e7bc0a8b34)
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/133024702/1afde424-c881-47e7-a548-f070aa7ab936)


```
pip install matplotlib==3.4.3
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement matplotlib==3.4.3 (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4)
ERROR: No matching distribution found for matplotlib==3.4.3
```
But I found the version of matplotlib under conda environment is 3.7.1. I'm not sure what is problem. Can you give me some advice?

**Comment by EricKutschera** [comment]
Here's the line for the error: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_settings.py#L103

The error seems to be about this string `EVM%20prediction%20ctg006730.305`. Based on the output I think that may be used as a gene name in your input. I was able to get a similar error message by putting `%20` in a gene name for the test data

Can you try making a copy of your input SE.MATS.JC.txt and then replacing `%20` with `_` in the copied file?

**Comment by CarrieBishop** [comment]
Thanks for your reply. According to your advice, I have solved the problem. I ran the software again and found that there are too many outputs in the file. Total number of pdf images in `Sashimi_plot` files up to 4000 and the run time of software was too long. It is difficult to find the useful results. Can you tell me how to reduce output in `Sashimi_plot` file and eliminate useless results?

**Comment by EricKutschera** [comment]
Here's a related post: https://github.com/Xinglab/rmats2sashimiplot/issues/47
> rmats2sashimiplot will plot all the events in the file given to it as input with -e. Instead of using an rMATS output file directly (like SE.MATS.JC.txt), you could make a copy (SE.MATS.JC.filtered.txt) and modify that file so that it only contains the events that you want to plot. Then run rmats2sashimiplot with -e SE.MATS.JC.filtered.txt


Here's an example of some code that parses the rmats output files if you want to write a script to filter your files: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_P/summary.py#L69
