### ISSUE TITLE
I do not know what is problem with my command. Does this program dependent on python,numpy and libgfortran.so.5? But I could not figure out how it does not work

### ISSUE THREAD

**Issue by hzxalan** [Xinglab/rmats2sashimiplot#97]
# LSBATCH: User input
#BSUB –J hzxtest
#BSUB -n 2
#BSUB -q fatA
#BSUB -o job.out
#BSUB –e job.err
#BSUB –R span[hosts=1]
~/anaconda3/bin/rmats2sashimiplot --b1 /public-supool/home/tong_lab/hzx/tophat/28shao/new/shao28/accepted_hits.bam,/public-supool/home/tong_lab/hzx/tophat/27
-6shao/new/shao27/accepted_hits.bam,/public-supool/home/tong_lab/hzx/tophat/shao2020/new/shao2020/accepted_hits.bam --b2 /public-supool/home/tong_lab/hzx/top
hat/27-6duo/new/duo27/accepted_hits.bam,/public-supool/home/tong_lab/hzx/tophat/28duo/new/duo28/accepted_hits.bam,/public-supool/home/tong_lab/hzx/tophat/duo
2020/new/duo2020/accepted_hits.bam -t A5SS -e /public-supool/home/tong_lab/hzx1/splicing2023/files/lessb1moreb2splicingoutput/A5SS.MATS.JC.txt --l1 less_spik
enumber --l2 more_spikenumber -o less_more_A5SS_plot_output
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   6410.30 sec.
    Max Memory :                                 -
    Average Memory :                             -
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              5
    Max Threads :                                6
    Run time :                                   6285 sec.
    Turnaround time :                            6286 sec.

The output (if any) follows:

Traceback (most recent call last):
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran.so.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/MISO/misopy/index_gff.py", line 21, in <module>
    import misopy.Gene as gene_utils
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/MISO/misopy/Gene.py", line 2, in <module>
    from scipy import *
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/scipy/__init__.py", line 73, in <module>
    from numpy import show_config as show_numpy_config
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/public-supool/home/tong_lab/anaconda3/bin/python"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libgfortran.so.5: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran.so.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 11, in <module>
    import matplotlib
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/matplotlib/__init__.py", line 126, in <module>
    import numpy
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/public-supool/home/tong_lab/anaconda3/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

thes errors happened for several, could your help me figure out what is problem with my command, thanks a lot !

**Comment by EricKutschera** [comment]
The first part of your command is `~/anaconda3/bin/rmats2sashimiplot`. The help page from the error message (https://numpy.org/devdocs/user/troubleshooting-importerror.html) has "Please make sure that you have activated your conda environment"

Once the conda environment is activated then you can run with just `rmats2sashimiplot` instead of `~/anaconda3/bin/rmats2sashimiplot`
